kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: centos
  commands:
  - echo "appdemo"
  - echo $USERNAME, $PASSWORD
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
