kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: centos
  settings:
    from_secret: BOT_TOKEN
    from_secret: CHAT_ID
    from_secret: MESSAGE
  commands:
  - yum install crul -y 
  - curl https://api.telegram.org/bot1798618176:AAHsp_sAwYp5ndnk4vifTuym6YYbifQ3Das/sendMessage?chat_id=-1001511975877&text=123
