kind: pipeline
type: docker
name: 我的第一次

steps:
- name: build
  image: centos
  settings:
    BOT_TOKEN:
      from_secret: bot
    CHAT_ID:
      from_secret: chat
    MESSAGE:
      rom_secret: message
  commands:
  - yum install curl -y
  - curl "https://api.telegram.org/bot{{ BOT_TOKE }}/sendMessage?chat_id={{ CHAT_ID }} &text={{ MESSAGE }}"
   
