kind: pipeline
type: docker
name: 我的第一次

steps:
- name: build
  image: centos
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
    BOT_TOKEN:
      from_secret: bot
    CHAT_ID:
      from_secret: chat
    MESSAGE:
      rom_secret: message
  commands:
  - yum install curl -y
  - expert BOT_TOKEN
  - expert CHAT_ID
  - expert MESSAGE
  - echo -e "BOT_TOKEN , CHAT_ID , MESSAGE"
  - echo -e "$BOT_TOKEN , $CHAT_ID , $MESSAGE \n"
  - echo -e "USERNAME, PASSWORD"
  - echo -e "$USERNAME, $PASSWORD \n"
  - echo "curl https://api.telegram.org/bot${BOT_TOKE}/sendMessage?chat_id=${CHAT_ID}&text=${MESSAGE} \n "
  - curl "https://api.telegram.org/bot${BOT_TOKE}/sendMessage?chat_id=${CHAT_ID}&text=${MESSAGE}"
   
