kind: pipeline
type: docker
name: 我的第一次

steps:
- name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: token
      to:
        from_secret: chatid 
      message: >
        GOOD.

    
        
