kind: pipeline
type: docker
name: 我的第一次

steps:
- name: build
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: token
    to:
      from_secret: chatid 
    message: >
      老鼠愛大米。

    
        
