kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: alpine
  settings:
    from_secret: BOT_TOKEN
    from_secret: CHAT_ID
    from_secret: MESSAGE
  commands:
  - curl http://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=${MESSAGE}
