 - name: 發送持續整合結果到告警頻道
    event:
      - push
      - pull_request
    image: appleboy/drone-telegram
    settings:
      BOT_TOKEN:
        from_secret: bot
      CHAT_ID:
        from_secret: chat
      MESSAGE:
        from_secret: message
      message:
        curl "https://api.telegram.org/bot{{BOT_TOKEN}}/sendMessage?chat_id={{CHAT_ID}}&text={{MESSAGE}}"
   
