kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: centos
  commands:
  - yum install curl -y
  - echo ${BOT_TOKEN} , ${CHAT_ID} , ${MESSAGE}
  - curl "https://api.telegram.org/bot$BOT_TOKEN/sendMessage?chat_id=$CHAT_ID&text=$MESSAGE"
  environment:
    BOT_TOKEN:
      from_secret: bot_token
    CHAT_ID:
      from_secret: chat_id
    MESSAGE:
      from_secret: message
